version: '3.8'

services:
  api:
    image: 'docker-spring-boot-postgres:latest'
    restart: always
    build:
      context: ./Hi-end-Systems-Test-Task/
    container_name: api
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testtask
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    build:
      context: ./database/
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testtask
    ports:
      - "5432:5432"
  ui:
    image: "nginx:latest"
    container_name: ui
    restart: always
    volumes:
      - "./Hi-end-Systems-Test-Task-FE:/usr/share/nginx/html"
    depends_on:
      - api
    ports:
      - "80:80"