spring:
  application:
    name: Hi-end-Systems-Test-Task
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: validate

testtask:
  jwt:
    secret: c3VwZXJzZWNyZXRzdHJpbmdmb3Jqd3RnZW5lcmF0aW9u
    lifetime: 3600
    issuer: testtask